// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jipyobjhsnmtjardfrim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppcHlvYmpoc25tdGphcmRmcmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDY5MzMsImV4cCI6MjA2NDM4MjkzM30.4WWIGs8x3lqSnpkWRa6ywB3dUEOOs8gKq5N5JR4PUL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);