// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjdyztgimsqjvfwqcmnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqZHl6dGdpbXNxanZmd3FjbW5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MTYzMDgsImV4cCI6MjA2NDM5MjMwOH0.jMVcXuUC4f_3LVyf5yk8vqNqEHnB6Q_wQ5S_ikHHaXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);