// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqeaksfqarpshjonzqdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxZWFrc2ZxYXJwc2hqb256cWR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjcwNzIsImV4cCI6MjA2MzkwMzA3Mn0.VOXVYPiP27e0fsxkBVRRBwM5mfm7XQleowqR-hAqMcs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);